# Temario

El Plan de clases detallado con actividades, recursos, plantillas, material de lectura esta disponible en pdf. Aquí listamos la organización de los temas y las habilidades que el alumno debe lograr.

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Temas                                                                                                                                                                                                                          | Objetivo                                                                                                                                                                                       |
+:===============================================================================================================================================================================================================================+:===============================================================================================================================================================================================+
| [Introducción a la bioinformática](https://lcg-cursos.github.io/material/introbioinfo/L3-shell.html#1)                                                                                                                         | -   Comprender qué es Unix, sus características principales y su utilidad en entornos científicos y técnicos.                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Conceptos Unix y GNU/Linux](https://lcg-cursos.github.io/material/introbioinfo/L3-shell.html#20) y [protocolos de internet](https://lcg-cursos.github.io/material/introbioinfo/L3-shell.html#1)                               | -   Identificar los principales protocolos de intercambio de datos en internet y entender su funcionamiento básico.                                                                            |
|                                                                                                                                                                                                                                | -   Aplicar el protocolo de transferencia de archivos (FTP/SFTP) y acceder a servidores remotos de forma segura y eficiente.                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mis primeros pasos en Bash ([archivos](https://lcg-cursos.github.io/material/introbioinfo/L3-shell.html#70) y [permisos](https://lcg-cursos.github.io/material/introbioinfo/L3-shell.html#90)) y creación de scripts completos | -   Comprender la estructura del sistema de archivos en Unix y saber desplazarse por él eficientemente.                                                                                        |
|                                                                                                                                                                                                                                | -   Conocer y aplicar comandos básicos para gestionar archivos y directorios.                                                                                                                  |
|                                                                                                                                                                                                                                | -   Identificar los tipos de archivos en Unix, visualizar su contenido y entender su manejo.                                                                                                   |
|                                                                                                                                                                                                                                | -   Utilizar herramientas para comprimir y descomprimir archivos.                                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Buenas prácticas en Bioinformática](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/Parte3.html)                                                                                                                         | -   Aplicar buenas prácticas en bioinformática para asegurar que los análisis sean reproducibles, claros y colaborativos, mediante código modular, documentación precisa y control de calidad. |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Introducción a Markdown](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/Parte4.html)                                                                                                                                    | -   Usar Markdown como formato estándar en bioinformática.                                                                                                                                     |
|                                                                                                                                                                                                                                | -   Comprender las fases del análisis de datos bioinformáticos.                                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Mis primeros pasos en Bash](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/Bash.html)                                                                                                                                   | -   Conocer los tipos de rutas, entorno de bash y Comandos básicos                                                                                                                             |
|                                                                                                                                                                                                                                | -   Modificar permisos                                                                                                                                                                         |
|                                                                                                                                                                                                                                | -   Comprimir y descomprimir archivos                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Análisis de datos de RNA-Seq](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/Rnaseq_intro.html#pipeline-general)                                                                                                        | -   introducción a bioinformática                                                                                                                                                              |
|                                                                                                                                                                                                                                | -   Idea principal de RNA-Seq                                                                                                                                                                  |
|                                                                                                                                                                                                                                | -   Pipeline general del análisis de datos de RNA-seq                                                                                                                                          |
|                                                                                                                                                                                                                                | -   Primeros pasos en el control de calidad de las lecturas                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Wildcards y Streams](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/REGEX.html)                                                                                                                                         | -   Caracteres y string                                                                                                                                                                        |
|                                                                                                                                                                                                                                | -   Wildcarts / comodines                                                                                                                                                                      |
|                                                                                                                                                                                                                                | -   Operadores de redirección de datos I/O                                                                                                                                                     |
|                                                                                                                                                                                                                                | -   Expresiones regulates                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Definición actualizada y didáctica del gen](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/genes_orf.html)                                                                                                              | -   ¿Qué es un gen?                                                                                                                                                                            |
|                                                                                                                                                                                                                                | -   Potencial codificante y marco de lectura. abierto (ORF)                                                                                                                                    |
|                                                                                                                                                                                                                                | -   Tipos de archivos comunes en bioinformática                                                                                                                                                |
|                                                                                                                                                                                                                                | -   Herramientas clave en bioinformática                                                                                                                                                       |
|                                                                                                                                                                                                                                | -   Pipeline de codificantes y no codificantes                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Scripts en Bash](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/ScriptBash.html)                                                                                                                                        | -   Extracción de información de archivos fastq, [fasta, GTF y BED](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/Anotation_ejercicios.html#archivo-fasta)                              |
|                                                                                                                                                                                                                                | -   [Aplicaciones](https://eveliacoss.github.io/LCG2025_IntroBioinfo_S1/Annotation_lncRNAs.html)                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
